### ISSUE TITLE
Lock files picked up as data

### ISSUE THREAD

**Issue by denniskpeters** [memorial-ece/CI_ReportGen#1]
If someone has a grades file open, there is a lock/tmp file created in the same directory, which is picked up as a matching file name:

```
DEBUG:root:Match with ~$PHYS 3000 Course Grade.xlsx resulted in <_sre.SRE_Match object; span=(2, 24), match='phys 3000 course grade'>
DEBUG:root:Search resulted in /Users/dpeters/Documents/Admin/ContinuousImprovement/CI_ReportGen/../Grades/ENCM/~$PHYS 3000 Course Grade.xlsx
DEBUG:root:Attempting to open passed-in file /Users/dpeters/Documents/Admin/ContinuousImprovement/CI_ReportGen/../Grades/ENCM/~$PHYS 3000 Course Grade.xlsx
WARNING:root:Unsupported format, or corrupt file: Expected BOF record; found b'\rDennis '
Skipping course and continuing
WARNING:root:Missing data stored in separate file
INFO:root:Autogeneration done!

```
The result is that no histogram is produced.

**Comment by rmletto** [comment]
The file searching has been updated to be more restrictive. It now needs to see course name as the very first thing in the file to get around the locking issue. Additionally, it needs to find a .xlsx file extension just in case the directories get polluted with other incompatible file formats.
